### ISSUE TITLE
mancitepar=false has no effect

### ISSUE THREAD

**Issue by wjordan** [jmclawson/biblatex-mla#12]
The 'mancitepar=false' feature doesn't seem to have any effect.
Sample code:
```
\documentclass{article}

\usepackage[american]{babel} 
\usepackage[style=mla,mancitepar=false]{biblatex}

\begin{filecontents}{\jobname.bib}
  @book{A01,
    author = {Author, A.},
    year = {2001},
    title = {Alpha},
  }
\end{filecontents}

\addbibresource{\jobname.bib}

\begin{document}
  ``text'' \autocite[1]{A01}.  

  ``text'' \autocite[2]{A01}.

  \printbibliography
\end{document}
```

The only workaround I managed to find is to remove the "mancitepar" entry from mla.cbx line 45 (\ExecuteBibliographyOptions), which sets mancitepar to `false` by default, making the above sample behave as expected.

**Comment by jmclawson** [comment]
I think I've figured out why it was misbehaving. A proper solution will need a new triggering mechanism, but your suggestion of setting it to false by default is preferable over keeping the problem live any longer. (Especially after 2 years...)
