### ISSUE TITLE
Doesn't work with the new version of biblatex

### ISSUE THREAD

**Issue by drewx0r** [jmclawson/biblatex-mla#14]
the current version of biblatex-mla doesn't work with biblatex's new nameparts syntax, so using it throws an error when reading the first instance of \usebibmacro. Will there be an updated version that contains this new syntax?

For reference, see the paragraph that begins with INCOMPATIBLE CHANGE:

http://ctan.math.utah.edu/ctan/tex-archive/macros/latex/contrib/biblatex/RELEASE

**Comment by jmclawson** [comment]
I've just merged a pull request from @gvdgdo to fix the issue, and I'll roll it out to CTAN today as a stable update.
