### ISSUE TITLE
Upcoming changes in biblatex 3.8: origlanguage becomes a list

### ISSUE THREAD

**Issue by moewew** [jmclawson/biblatex-mla#16]
In the upcoming (and as of now unreleased) version 3.8 of `biblatex` `origlanguage` will change its type from `field` to `list`.

Both `mla.bbx` and `mla-new.bbx` check if `origlanguage` is empty
https://github.com/jmclawson/biblatex-mla/blob/9b1085ed3ff9eb6adbc13e1d915d4eee7aedce0f/mla.bbx#L436
https://github.com/jmclawson/biblatex-mla/blob/9b1085ed3ff9eb6adbc13e1d915d4eee7aedce0f/mla-new.bbx#L448
with `\iffieldundef{origlanguage}` that should probably now be `\iflistundef{origlanguage}`.

For background info see https://github.com/plk/biblatex/issues/594

You might also want to have a look at the other changes in 3.8 https://github.com/plk/biblatex/blob/dev/doc/latex/biblatex/CHANGES.org

**Comment by moewew** [comment]
`biblatex` 3.8 is on track for release quite soon.

**Comment by frigaardj** [comment]
Just made a PR for this.
