### ISSUE TITLE
Movie driver missing

### ISSUE THREAD

**Issue by lovesegfault** [jmclawson/biblatex-mla#17]
The `@movie` entry, which biblatex supports, is not yet available.

**Comment by jmclawson** [comment]
I'll be adding this to the next release. (Sorry for silence. I do work on this project intermittently.)

**Comment by lovesegfault** [comment]
@jmclawson That's awesome, thank you! And thank you for your work on this, an absolute life saver for my GenEd classes in College!

**Comment by jmclawson** [comment]
Added in 2.0 (readying for release)
