### ISSUE TITLE
Article database citation non-compliant?

### ISSUE THREAD

**Issue by legowave440** [jmclawson/biblatex-mla#19]
I recently found a case where the database field of a bibtex entry is cited against [MLA guidelines](https://owl.purdue.edu/owl/research_and_citation/mla_style/mla_formatting_and_style_guide/mla_works_cited_electronic_sources.html), as shown by [this stackexchange question](https://tex.stackexchange.com/questions/480562/bibtex-mla-not-compliant-with-mla). Typically, the database field is to be cited before the URL, but the default behavior of the biblatex-mla package is to cite it after the link. A temporary workaround was provided by [moewe](https://tex.stackexchange.com/users/35864/moewe) in [this answer](https://tex.stackexchange.com/questions/480562/bibtex-mla-not-compliant-with-mla#answer-480636), which was to modify a macro:

    \renewbibmacro*{mla:container:one}{%
      \usebibmacro{mla:article:journal+issuetitle}%
      \newunit\newblock
      \printfield{note}%
      \newunit%
      \printfield{pages}%
      \newunit%
      \iffieldundef{eprinttype}
        {\setunit{\addperiod\space}%
         \printfield{eprint}
         \setunit{\addcomma\space}%
         \clearfield{eprint}%
         \usebibmacro{url+urldate}}%
        {}%
      \printunit{\addperiod\space}\newblock%
    }

**Comment by jmclawson** [comment]
Thank you for this. I think this problem is a leftover from the transition to the new MLA style. I'll be sure to fix it in the next update, but I'm glad you found something that works for now.

**Comment by Sandropology** [comment]
Hey, this is perfect. I was just about to post the exact same problem. Just posting here so I'll get notified once it's solved.

**Comment by jmclawson** [comment]
Fixed in the next release
