### ISSUE TITLE
bycomposer undefined

### ISSUE THREAD

**Issue by u-fischer** [jmclawson/biblatex-mla#31]
The following example errors in a current texlive 2021 with biblatex 3.17 and biblatex-mla v2.1a:

~~~~
\documentclass{article}
\usepackage[style=mla7]{biblatex}
\addbibresource{biblatex-examples.bib}
\begin{document}
\textcite{doody}
\end{document}
~~~~

~~~~
! Package keyval Error: bycomposer undefined.

See the keyval package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.159 }
~~~~

**Comment by jmclawson** [comment]
Thanks for catching this! The mla7 style is mostly out of date, so I don't check it as carefully, but it's worth keeping in sync. I've corrected it on GitHub and will roll it into the next version to head to CTAN.
